# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb59786c44bad6e82c0adcaca8069d5b3269d5ea05b50234b7abdcd258d97a1f7326b8c5aaa61487db5b43fd5abaf2292a18ad17cf50114ebaa9c036811cb756

test:
  secret_key_base: 7dcef36513ca008d28dad6d370cc6e00217d3deae9028922a1ad51d86c97f252cbcca0e59b99baeded662b0d98d79b3b50b4c8b18b9cef13c6e7a38243d4e79f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
